services:
  - type: web
    name: copy_clip_server
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000